# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
